### PR TITLE
refactored check for dmagic orbital science

### PR DESCRIPTION
**Pull request by Sephiroth018**
refactored the check for dmagic orbital science experiment executability
to use dmagic's provided conduct method
also refactored debug logging to be automatically enabled when built
with the DEBUG constant

### CODE REVIEW

**Comment by Xarun** [comment]
tested this code and conductMethod is always false in my testcase

**Comment by Sephiroth018** [comment]
That's interesting, I have succesfully tested it on my machine. Maybe it depends on the experiment, which one did you use? I tested it with the universal storage parts of the following experiments: 1 magnetometer boom, 1 mystery goo and 2 material studies

**Comment by Xarun** [comment]
Testcase: Station around the mun with "US - Solar Particle Collector"(universal storage part).
I didnt try the other parts cause i thought they would give out the same results which is interesting

**Comment by Sephiroth018** [comment]
Maybe the solar particle collector behaves different because it can store multiple experiments. I will try it with my machine.

**Comment by Xarun** [comment]
I will merge this for now.I will readd the check with the experiment limit ,but we should try to find a better way to check the solar particle experiment

**Pull request merged**
